import { Inter } from "next/font/google";
import "./styles/globals.css";
import Navbar from "./components/Layout/Navbar";
import Head from "next/head";
import Menubar from "./components/Layout/Menubar";
import Footer from "./components/Layout/Footer";
import FasilitiesCard from "./components/UI/FasilitiesCard";
import Image from "next/image";
import subscriptionBanner from "@/public/images/banner-9-min.png";
import icon1 from "@/public/images/icon-1.png";
import icon2 from "@/public/images/icon-2.png";
import icon3 from "@/public/images/icon-3.png";
import icon4 from "@/public/images/icon-4.png";
import icon5 from "@/public/images/icon-5.png";
import Providers from "@/lib/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kotky",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <Head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
            integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
          />
        </Head>
        <body className={`${inter.className}`}>
          <Navbar />
          <Menubar />
          {children}
          <div className="px-3">
            <div className="bgSubccription lg:my-10 rounded-[20px] relative w-full min-h-[230px]">
              <div className="lg:px-[78px] p-7 lg:py-[84px]">
                <h1 className="mb-5 text-2xl lg:text-7xl leading-none text-[#253D4E] font-bold">
                  Stay home &amp; get your daily
                  <br />
                  needs from our shop
                </h1>
                <p className="font-lato text-sm md:text-lg mb-[45px]">
                  Start Your Daily Shopping with{" "}
                  <span className="font-lato text-[#3BB77E]">Nest Mart</span>
                </p>
                <div className="bg-white max-w-[450px] rounded-[50px] h-16 flex relative z-10">
                  <input
                    type="email"
                    placeholder="Your Email Address"
                    className="w-full h-full rounded-[50px] px-[30px] font-lato border-none outline-none placeholder:font-bold"
                  />
                  <button className="h-full rounded-[50px] px-[30px] border-none outline-none text-base  bg-[#3BB77E] text-white">
                    subscribe
                  </button>
                </div>
              </div>
              <Image
                src={subscriptionBanner}
                className="w-2/5 absolute bottom-0 right-[50px]"
                alt=""
              />
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-5 mt-5">
              <FasilitiesCard
                image={icon1}
                title="Best prices &amp; offers"
                text="Orders $50 or more"
              />
              <FasilitiesCard
                image={icon2}
                title={"Free Delivery"}
                text={"24/7 amazing services"}
              />
              <FasilitiesCard
                image={icon3}
                title={"Great daily deal"}
                text={"When you sign up"}
              />
              <FasilitiesCard
                image={icon4}
                title={"Wide assortment"}
                text={"Mega Discounts"}
              />
              <FasilitiesCard
                image={icon5}
                title={"Easy returns"}
                text={"Within 30 days"}
              />
            </div>
          </div>
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
